Adding redux
ZacMiddleton/crypto-app pull request #15
Opened 2023-05-31 18:06 UTC by ZacMiddleton

adding redux to application. entire app not converted to redux yet in process.

2023-05-31 20:55 UTC, yoloOnTheBattlefield requested changes

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/components/ConversionCalculator/ConversionCalculator.styles.jsx
> +  // width: 270px;
remove this

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/components/CryptoTable/index.jsx
> +                )}${new Intl.NumberFormat().format(item.current_price)}`}</p>
put this in a utility fn

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/pages/Coins/Coins.jsx
> +const mapStateToProps = (state) => ({
use the redux hooks

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/store/coinData/index.jsx
> +    console.log(state);
remove this

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/App.jsx
> +  console.log(coinData);
remove this

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/store/coinData/actions.jsx
> +    console.log("called");
remove this

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/App.jsx
> +}
use the hooks

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/components/BtcBarChart/index.jsx
> +})
use the hooks

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/components/BtcLineChart/index.jsx
> +})
use the hooks

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/components/CryptoTable/index.jsx
> +})
use the hooks

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/components/Root/index.jsx
> +});
use the hooks

2023-05-31 20:55 UTC, yoloOnTheBattlefield commented on src/pages/CoinPage/CoinPage.jsx
> +})
use the hooks

2023-06-04 20:57 UTC, ZacMiddleton commented on src/pages/Coins/Coins.jsx
> +const mapStateToProps = (state) => ({
coins is a class component, im going to convert it to hooks and make a separate pull request for that

2023-06-07 22:50 UTC, merged